# -*- coding: utf-8 -*-
"""World_Inflation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tTsRpF4m-MfI1pWp0iVHIVp-U3lfhZJQ
"""

!pip install country_converter

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import requests
from country_converter import CountryConverter
import textwrap

import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Datasets/inflation_cost_of_living_dataset.csv")
df.head()

def demarcation():
    print("---" * 20)
    print("***" * 20)
    print("---" * 20)

demarcation()
print("Dataset shape is : ", df.shape)
demarcation()
print(df.isna().sum())
demarcation()
print(df.info())

demarcation()
print(df.isna().sum())
demarcation()
print(df.isna().sum()/len(df) *100)
demarcation()

#Drop columns with greater than 50% missing values
null_pct = df.isna().sum()/len(df) *100
# null_pct.index
drop_cols = [col for col in null_pct.index if null_pct[col] > 50]
drop_cols
demarcation()

df_data = df.drop(columns=drop_cols)
demarcation()
print(df_data.info())
demarcation()

cc = CountryConverter()
df_data['IS03_country'] = cc.convert(df_data['country'], to="iso3")
df_data.head()

df_data.info()

#df_data["IS03_country"].value_counts().sort_values(ascending=False)

#Clean inflation year column
years = df_data['inflation_year'].astype("str")
corr_year = [year.split(".")[0] for year in years]
df_data['inflation_year'] = corr_year
df_data['inflation_year'] = df_data['inflation_year'].replace("nan", np.nan)
df_data.head()



demarcation()
print("")
print("Unique regions in dataset")
print("")
print(df_data['region'].unique())
demarcation()
df_data['region'].value_counts()

"""#EXPLORATORY DATA ANALYSIS"""

fig, ax = plt.subplots(figsize=(10,5))
plt.hist(x = df_data['inflation_annual_pct'], bins=15)
plt.xlabel("Annual Inflation Rate")
plt.ylabel("Frequency [Count]")
plt.title("Distribution of Annual Inflation Rate")
plt.show()

fig, ax = plt.subplots(figsize=(10,5))
sns.boxplot(x=df_data['inflation_annual_pct'], ax=ax)
plt.xlabel("Annual Inflation Rate")
plt.ylabel("Frequency [Count]")
plt.title("Distribution of Annual Inflation Rate")
plt.show()

demarcation()
print("Inflation Year Distribtion")
print("")
print(df_data['inflation_year'].value_counts())
demarcation()

fig, ax = plt.subplots(figsize=(10,5))
df_data['inflation_year'].value_counts().plot(kind = "bar", ax=ax)
plt.xlabel("Inflation Year")
plt.ylabel("Frequency  [Count]")
plt.title("Distribution of Inflation-year")
plt.show()

fig, ax = plt.subplots(figsize=(10,5))
#sns.countplot(data=df_data, x="region", axes=ax)
df_data['region'].value_counts().plot(kind="bar", ax=ax)
plt.xticks(rotation = 90)
plt.xlabel("Geographical Regions")
plt.ylabel("Frequency [Count]")
plt.title("Distribution of Countries by Region", y=1.05)
plt.show()

income_inflation = df_data.groupby("income_level")["inflation_annual_pct"].mean().sort_values()
income_inflation

fig = px.bar(
    data_frame = income_inflation,
    x = income_inflation.index,
    y = income_inflation.values,
    color = income_inflation.values,
    color_continuous_scale= px.colors.sequential.Blues,
    title = "Annual-Inflation Rate Categorized by Income Level of Contries")
fig.update_layout(
    xaxis_title = "Income Level",
    yaxis_title = "Annual Inflation Rate"
)
fig.show()

df_data.groupby(["income_level", "region"])["country"].size()

mask = df_data['income_level'] == "Low income"
mask_b = df_data['income_level'] == "Lower middle income"
mask_c = df_data['income_level'] == "Upper middle income"
mask_d = df_data['income_level'] == "High income"

low_income = df_data[mask]
lower_middle_income = df_data[mask_b]
upper_middle_income = df_data[mask_c]
high_income = df_data[mask_d]

#Plot of ditribution of countries by income levels
fig, ax = plt.subplots(1,2, figsize=(15,5))

#lower_middle_income['region'].value_counts().plot(kind="bar", ax=ax[1,0])
#upper_middle_income['region'].value_counts().plot(kind="bar", ax=ax[1,1])

low_income['region'].value_counts().plot(kind="bar", ax=ax[0])
labels = [
    textwrap.fill(label.get_text(), width=10)
    for label in ax[0].get_xticklabels() ]
ax[0].set_xticklabels(labels)
ax[0].set_ylabel("Frequency [Count]")
ax[0].set_xlabel("Region")
ax[0].set_title("Low Income Countries by Region")


high_income['region'].value_counts().plot(kind="bar", ax=ax[1])
labels = [
    textwrap.fill(label.get_text(), width=10)
    for label in ax[1].get_xticklabels() ]
ax[1].set_xticklabels(labels)
ax[1].set_xlabel("Region")
ax[1].set_title("High Income Countries by Region")

#plt.xticks(rotation = 90)
#plt.xlabel("Geographical Regions")


plt.suptitle("Income of Countries by Region", y=1.05)
plt.tight_layout()
plt.show()

#Chexk Sub-Saharan High Income Country
high_income["region"] = (
    high_income["region"]
    .astype(str)
    .str.strip()
)

df_data["region"] = df_data["region"].str.strip()

maska = high_income['region'] ==  "Sub-Saharan Africa"
high_income[maska]



#categorize inflation by region
region_inflation = df_data.groupby("region")["inflation_annual_pct"].mean().sort_values()
region_inflation

fig = px.bar(
    data_frame = region_inflation,
    x = region_inflation.index,
    y = region_inflation.values,
    color = region_inflation.values,
    color_continuous_scale= px.colors.sequential.Reds,
    title = "Annual Inflation Rate by Region"
)
fig.update_layout(
    xaxis_title = "Region",
    yaxis_title = "Annual Inflation Rate"
)
fig.show()

fig =px.scatter_mapbox(
    data_frame = df_data,
    lat = "latitude",
    lon = "longitude",
    color = "inflation_annual_pct",
    color_continuous_scale= px.colors.sequential.Reds,
    center= {"lat":10, "lon":15},
    hover_name="country",
    hover_data=[
        "region",
        "income_level"
    ],
    zoom = 1,
    mapbox_style="open-street-map",
    title= "Annual Inflation Rate by Country"

)
fig.show()



fig = px.choropleth(
    data_frame = df_data,
    locations = "IS03_country",
    #projection = "orthographic",
    projection = "robinson",
    #projection = "equirectangular",
    color = "inflation_annual_pct",
    color_continuous_scale= px.colors.sequential.Reds,
    title = "Inflation By Country"
)

fig.show()

#filter out top 30 countries with inflation
top_30 = df_data.sort_values(by=["inflation_annual_pct"], ascending=False).head(30).reset_index().drop(columns="index")

fig,(ax,ax2) = plt.subplots(1, 2, figsize=(20,5))
sns.barplot(data=top_30, x="country", y="inflation_annual_pct", ax=ax, hue="inflation_annual_pct")
sns.lineplot(data=top_30, x="country", y="inflation_annual_pct", ax=ax, color="brown", linestyle="--", linewidth="2")
ax.set_xlabel("Country")
ax.set_ylabel("Annual Inflation Rate")
ax.tick_params(axis="x", rotation=90)
ax.set_title("Top 30 Countries with Highest Inflation Rate")

sns.barplot(data=top_30, x="country", y="inflation_annual_pct", ax=ax2, hue="region")
ax2.set_xlabel("Country")
ax2.set_ylabel("Annual Inflation Rate")
ax2.set_title("Top 30 Countries by Region")
ax2.tick_params(axis="x", rotation=90)

sns.despine()
plt.suptitle("Top 30 Countries with Highest Inflation Rate")
plt.show()

fig = px.bar(
    data_frame = top_30.head(10),
    x = "country",
    y = "inflation_annual_pct",
    color = "inflation_annual_pct",
    color_continuous_scale= px.colors.sequential.Reds,
    title = "Top 10 Countries with Highest Inflation Rate"
)
fig.update_layout(
    xaxis_title = "Country",
    yaxis_title = "Annual Inflation Rate"
)
fig.show()













"""#CONCLUSION"""

